package com.ehealthwares.rxsoft.ui.items

import android.content.Context
import android.net.Uri
import android.util.Log
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.ehealthwares.rxsoft.data.local.CategoryDao
import com.ehealthwares.rxsoft.data.local.UomDao
import com.ehealthwares.rxsoft.data.remote.dto.CategoryDto
import com.ehealthwares.rxsoft.data.remote.dto.CreateItemRequest
import com.ehealthwares.rxsoft.data.remote.dto.ItemDto
import com.ehealthwares.rxsoft.data.remote.dto.PatchItemRequest
import com.ehealthwares.rxsoft.data.remote.dto.UomDto
import com.ehealthwares.rxsoft.data.repository.PosRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File
import java.math.BigDecimal
import javax.inject.Inject

data class ItemFormState(
    val isLoading: Boolean = false,
    val isSaving: Boolean = false,
    val isUploadingImage: Boolean = false,
    val item: ItemDto? = null,
    val categories: List<CategoryDto> = emptyList(),
    val uoms: List<UomDto> = emptyList(),
    /** Free-text typed into the category field; drives debounced server search. */
    val categoryQuery: String = "",
    /** Search text inside the UOM dialog; drives debounced server search. */
    val uomQuery: String = "",
    val code: String = "",
    val name: String = "",
    val barcode: String = "",
    /** Chosen category id — only set by picking from the list, never by typing. */
    val categoryId: String = "",
    val baseUomId: String = "",
    val purchaseUomId: String = "",
    val saleUomId: String = "",
    val alias: String = "",
    val genericProductCode: String = "",
    val genericDrugCode: String = "",
    val trackLot: Boolean = true,
    val trackExpiry: Boolean = true,
    val shelfLifeDays: String = "",
    val isActive: Boolean = true,
    val imageUrl: String? = null,
    val error: String? = null,
    /** Load failure for the category/UOM reference lists (offline, API error…). */
    val refError: String? = null,
    val saved: Boolean = false,
    /** Tracks whether the code was auto-generated so name changes can regenerate it. */
    val autoGeneratedCode: Boolean = false
)

@HiltViewModel
class ItemFormViewModel @Inject constructor(
    @ApplicationContext private val context: Context,
    private val posRepository: PosRepository,
    private val categoryDao: CategoryDao,
    private val uomDao: UomDao
) : ViewModel() {

    private val _state = MutableStateFlow(ItemFormState())
    val state: StateFlow<ItemFormState> = _state.asStateFlow()

    private var categorySearchJob: Job? = null
    private var uomSearchJob: Job? = null

    fun load(itemId: String?) {
        viewModelScope.launch {
            _state.value = _state.value.copy(isLoading = true)

            loadCategories("")
            loadUoms("")

            if (itemId != null) {
                posRepository.getItem(itemId)
                    .onSuccess { item ->
                        _state.value = _state.value.copy(
                            isLoading = false,
                            item = item,
                            code = item.code ?: "",
                            name = item.name,
                            barcode = item.barcode ?: "",
                            categoryId = item.category?.id ?: "",
                            baseUomId = item.baseUomId ?: "",
                            purchaseUomId = item.baseUomId ?: "",
                            saleUomId = item.baseUomId ?: "",
                            isActive = true,
                            imageUrl = item.imageUrl
                        )
                    }
                    .onFailure {
                        _state.value = _state.value.copy(isLoading = false, error = it.message)
                    }
            } else {
                // New item: auto-generate a code from name initials + hex suffix
                val autoCode = generateItemCode("")
                _state.value = _state.value.copy(
                    isLoading = false,
                    code = autoCode,
                    autoGeneratedCode = true
                )
            }
        }
    }

    /**
     * Fetch categories for [query] (blank = all). Falls back to the Room cache
     * when the API is unreachable so the form still works offline.
     */
    private suspend fun loadCategories(query: String) {
        posRepository.getCategories(query.ifBlank { null })
            .onSuccess { cats ->
                _state.value = _state.value.copy(categories = cats, refError = null)
            }
            .onFailure { e ->
                val cached = withContext(Dispatchers.IO) { categoryDao.all() }
                if (cached.isNotEmpty()) {
                    _state.value = _state.value.copy(
                        categories = cached.map { CategoryDto(id = it.id, name = it.name) },
                        refError = null
                    )
                } else {
                    Log.w(TAG, "Could not load categories", e)
                    _state.value = _state.value.copy(refError = e.message ?: "Could not load categories")
                }
            }
    }

    /** Fetch uoms for [query] (blank = all), with the same Room fallback. */
    private suspend fun loadUoms(query: String) {
        posRepository.getUoms(query.ifBlank { null })
            .onSuccess { uomList ->
                _state.value = _state.value.copy(uoms = uomList, refError = null)
            }
            .onFailure { e ->
                val cached = withContext(Dispatchers.IO) { uomDao.all() }
                if (cached.isNotEmpty()) {
                    _state.value = _state.value.copy(
                        uoms = cached.map {
                            UomDto(
                                id = it.id,
                                code = it.code,
                                name = it.name,
                                categoryId = it.categoryId,
                                uomType = it.uomType,
                                factor = BigDecimal(it.factor),
                                rounding = BigDecimal(it.rounding),
                                isActive = it.isActive
                            )
                        },
                        refError = null
                    )
                } else {
                    Log.w(TAG, "Could not load uoms", e)
                    _state.value = _state.value.copy(refError = e.message ?: "Could not load UOMs")
                }
            }
    }

    /**
     * Typed text in the category field: re-searches the server (debounced).
     * The chosen category id is untouched until the user picks from the list.
     */
    fun updateCategoryQuery(value: String) {
        _state.value = _state.value.copy(categoryQuery = value)
        categorySearchJob?.cancel()
        categorySearchJob = viewModelScope.launch {
            delay(SEARCH_DEBOUNCE_MS)
            if (_state.value.categoryQuery != value) return@launch
            loadCategories(value)
        }
    }

    /** Search text inside the UOM dialog (debounced). */
    fun updateUomQuery(value: String) {
        _state.value = _state.value.copy(uomQuery = value)
        uomSearchJob?.cancel()
        uomSearchJob = viewModelScope.launch {
            delay(SEARCH_DEBOUNCE_MS)
            if (_state.value.uomQuery != value) return@launch
            loadUoms(value)
        }
    }

    /** Opening the dialog resets the query and reloads the full list. */
    fun openCategoryDialog() {
        _state.value = _state.value.copy(categoryQuery = "")
        viewModelScope.launch { loadCategories("") }
    }

    /** Opening the dialog resets the query and reloads the full list. */
    fun openUomDialog() {
        _state.value = _state.value.copy(uomQuery = "")
        viewModelScope.launch { loadUoms("") }
    }

    /**
     * Generate an item code: uppercase initials of each word in [name] + "-" + 6-char hex.
     * If name is blank, returns just the hex suffix with a placeholder prefix.
     */
    private fun generateItemCode(name: String): String {
        val suffix = java.security.SecureRandom().let { rng ->
            val bytes = ByteArray(3)
            rng.nextBytes(bytes)
            bytes.joinToString("") { "%02x".format(it) }
        }
        val initials = name.trim().split(Regex("\\s+"))
            .filter { it.isNotEmpty() }
            .map { it.first().uppercaseChar() }
            .take(4)
            .joinToString("")
        return if (initials.isNotEmpty()) "$initials-$suffix" else "ITEM-$suffix"
    }

    fun updateCode(value: String) { _state.value = _state.value.copy(code = value, autoGeneratedCode = false) }

    fun updateName(value: String) {
        val s = _state.value
        // If code is still the auto-generated one, regenerate it from the new name
        val newCode = if (s.autoGeneratedCode) generateItemCode(value) else s.code
        _state.value = s.copy(name = value, code = newCode)
    }

    fun updateBarcode(value: String) { _state.value = _state.value.copy(barcode = value) }
    fun updateAlias(value: String) { _state.value = _state.value.copy(alias = value) }
    fun updateGenericProductCode(value: String) { _state.value = _state.value.copy(genericProductCode = value) }
    fun updateGenericDrugCode(value: String) { _state.value = _state.value.copy(genericDrugCode = value) }
    fun updateTrackLot(value: Boolean) { _state.value = _state.value.copy(trackLot = value) }
    fun updateTrackExpiry(value: Boolean) { _state.value = _state.value.copy(trackExpiry = value) }
    fun updateShelfLifeDays(value: String) { _state.value = _state.value.copy(shelfLifeDays = value) }

    /**
     * User picked a category from the list: store its id and show its name in
     * the field.
     */
    fun selectCategory(id: String) {
        _state.value = _state.value.copy(categoryId = id)
    }

    /**
     * Selecting a UOM fills base, purchase, and sale UOMs to the same value.
     */
    fun selectUom(id: String) {
        _state.value = _state.value.copy(
            baseUomId = id,
            purchaseUomId = id,
            saleUomId = id
        )
    }

    fun updateIsActive(value: Boolean) { _state.value = _state.value.copy(isActive = value) }

    fun uploadImage(uri: Uri) {
        viewModelScope.launch {
            _state.value = _state.value.copy(isUploadingImage = true)
            val tempFile = withContext(Dispatchers.IO) {
                val inputStream = context.contentResolver.openInputStream(uri) ?: return@withContext null
                val outFile = File(context.cacheDir, "upload_${System.currentTimeMillis()}.jpg")
                outFile.outputStream().use { output ->
                    inputStream.copyTo(output)
                }
                inputStream.close()
                outFile
            }
            if (tempFile == null) {
                _state.value = _state.value.copy(isUploadingImage = false, error = "Could not read image")
                return@launch
            }
            posRepository.uploadImage(tempFile)
                .onSuccess { response ->
                    tempFile.delete()
                    _state.value = _state.value.copy(
                        isUploadingImage = false,
                        imageUrl = response.url
                    )
                }
                .onFailure {
                    tempFile.delete()
                    _state.value = _state.value.copy(
                        isUploadingImage = false,
                        error = it.message ?: "Image upload failed"
                    )
                }
        }
    }

    fun clearImage() {
        _state.value = _state.value.copy(imageUrl = null)
    }

    fun save() {
        val s = _state.value
        val creating = s.item == null
        if (s.name.isBlank() || (creating && (s.categoryId.isBlank() || s.baseUomId.isBlank()))) {
            _state.value = s.copy(
                error = when {
                    s.name.isBlank() -> "Name is required"
                    s.categoryId.isBlank() -> "Select a category from the list"
                    else -> "Select a UOM from the list"
                }
            )
            return
        }

        viewModelScope.launch {
            _state.value = _state.value.copy(isSaving = true, error = null)

            val existing = s.item
            if (existing != null) {
                posRepository.updateItem(
                    existing.id,
                    PatchItemRequest(
                        code = s.code.ifBlank { null },
                        name = s.name,
                        categoryId = s.categoryId,
                        barcode = s.barcode.ifBlank { null },
                        isActive = s.isActive,
                        imageUrl = s.imageUrl,
                        baseUomId = s.baseUomId.ifBlank { null },
                        saleUomId = s.saleUomId.ifBlank { null },
                        purchaseUomId = s.purchaseUomId.ifBlank { null },
                    )
                ).onSuccess { _state.value = _state.value.copy(isSaving = false, saved = true) }
                 .onFailure { _state.value = _state.value.copy(isSaving = false, error = it.message) }
            } else {
                posRepository.createItem(
                    CreateItemRequest(
                        code = s.code.ifBlank { null },
                        name = s.name,
                        categoryId = s.categoryId,
                        baseUomId = s.baseUomId,
                        purchaseUomId = s.purchaseUomId.ifBlank { null },
                        saleUomId = s.saleUomId.ifBlank { null },
                        barcode = s.barcode.ifBlank { null },
                        isActive = s.isActive,
                        imageUrl = s.imageUrl,
                        alias = s.alias.ifBlank { null },
                        genericProductCode = s.genericProductCode.ifBlank { null },
                        genericDrugCode = s.genericDrugCode.ifBlank { null },
                        trackLot = s.trackLot,
                        trackExpiry = s.trackExpiry,
                        shelfLifeDays = s.shelfLifeDays.toIntOrNull()
                    )
                ).onSuccess { _state.value = _state.value.copy(isSaving = false, saved = true) }
                 .onFailure { _state.value = _state.value.copy(isSaving = false, error = it.message) }
            }
        }
    }

    fun clearError() { _state.value = _state.value.copy(error = null, refError = null) }

    companion object {
        private const val TAG = "ItemFormVM"
        private const val SEARCH_DEBOUNCE_MS = 250L
    }
}
